# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('isstateexprence', models.SmallIntegerField(default=0)),
                ('systemcode', models.CharField(max_length=20)),
                ('compartmentcode', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Vouchs',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('sdate', models.DateField()),
                ('begindate', models.DateField()),
                ('enddate', models.DateField()),
                ('count', models.IntegerField()),
                ('subsdep', models.CharField(max_length=200)),
                ('big', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'vouchs',
            },
        ),
    ]
