# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shanxidaily', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comdartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('susdepname', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'comdartment',
            },
        ),
        migrations.CreateModel(
            name='dailyinfo',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=101, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('banshu', models.IntegerField()),
                ('url', models.CharField(max_length=500)),
                ('info', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'dailyinfo',
            },
        ),
        migrations.CreateModel(
            name='susDep',
            fields=[
                ('susdepname', models.CharField(max_length=200)),
                ('susdepcode', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'susdep',
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='compartmentcode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='systemcode',
        ),
        migrations.AddField(
            model_name='vouchs',
            name='customer',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='shanxidaily.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='CompartmentCode',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='shanxidaily.susDep'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='SystemCode',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='shanxidaily.Comdartment'),
            preserve_default=False,
        ),
    ]
