# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shanxidaily', '0002_auto_20170617_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='CompartmentCode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='SystemCode',
        ),
        migrations.AddField(
            model_name='customer',
            name='compartmentcode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='departmentname',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='systomcode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='isstateexprence',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
