# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shanxidaily', '0003_auto_20170618_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchs',
            name='fee',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
