# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shanxidaily', '0004_vouchs_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='compatment',
            field=models.ForeignKey(default='610100000000', on_delete=django.db.models.deletion.CASCADE, to='shanxidaily.susDep'),
            preserve_default=False,
        ),
    ]
